apiVersion: v1
kind: Namespace
metadata:
  name: brewery
---
apiVersion: v1
kind: Secret
metadata:
  name: brewery-secret
  namespace: brewery
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: brewery-configmap
  namespace: brewery
data:
  mongo-host: 'mongodb-service.mongo'
  mongo-port: '27017'
  mongo-database: 'brewery'
  kafka-servers: 'kafka-svc.kafka-kraft:9092'
  redis-host: 'redis-master.redis'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beer-service
  namespace: brewery
  labels:
    app: beer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beer-service
  template:
    metadata:
      labels:
        app: beer-service
    spec:
      containers:
        - name: beer-service
          image: shubhamgoel23/beer-service
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: brewery-secret
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: brewery-secret
                  key: mongo-root-password
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: brewery-configmap
                  key: mongo-host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: brewery-configmap
                  key: mongo-port
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: brewery-configmap
                  key: mongo-database
            - name: KAFKA_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: brewery-configmap
                  key: kafka-servers
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: brewery-configmap
                  key: redis-host
---
apiVersion: v1
kind: Service
metadata:
  name: beer-service
  namespace: brewery
spec:
  selector:
    app: beer-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080