apiVersion: v1
kind: ConfigMap
metadata:
  name: brewery-configmap
  namespace: brewery
data:
  mongo-host: 'mongodb-service.mongo'
  mongo-port: '27017'
  mongo-database: 'brewery'
  kafka-servers: 'kafka-svc.kafka-kraft:9092'
  redis-host: 'redis-master.redis'