apiVersion: v1
kind: Namespace
metadata:
  name: brewery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beer-service
  namespace: brewery
  labels:
    app: beer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beer-service
  template:
    metadata:
      labels:
        app: beer-service
    spec:
      containers:
        - name: beer-service
          image: shubhamgoel23/beer-service:af1908a
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: brewery-secret
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: brewery-secret
                  key: mongo-root-password
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: brewery-configmap
                  key: mongo-host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: brewery-configmap
                  key: mongo-port
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: brewery-configmap
                  key: mongo-database
            - name: KAFKA_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: brewery-configmap
                  key: kafka-servers
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: brewery-configmap
                  key: redis-host
---
apiVersion: v1
kind: Service
metadata:
  name: beer-service
  namespace: brewery
spec:
  selector:
    app: beer-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080