spring:
  application:
    name: order-service
  data.mongodb:
    authentication-database: admin
    username: username
    password: password
    database: brewery
  profiles:
    include:
      - common
    active:
      - beer-client-service

server:
  port: 8082

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true

spring.kafka.bootstrap-servers: localhost:9092