spring:
  application:
    name: order-service
  data.mongodb:
    authentication-database: admin
    username: username
    password: password
    database: brewery
  profiles:
    include:
      - common
    active:
      - mongo-db
      - beer-client-service

server:
  port: ${DEFAULT__APP__PORT:8082}

spring.kafka.bootstrap-servers: localhost:9092