services:
  mongo:
    image: mongo:latest
    restart: always
    hostname: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  redis:
    image: redis/redis-stack:latest
    restart: always
    hostname: redis
    ports:
      - 6379:6379
      - 8001:8001

  kafka:
    image: bashj79/kafka-kraft
    restart: always
    hostname: kafka
    ports:
      - 9092:9092