spring:
  data.mongodb:
    authentication-database: admin
    username: username
    password: password
    database: inventory
  graphql.graphiql:
    enabled: true
  profiles:
    include:
      - common
management.health.circuitbreakers.enabled: true
management:
  endpoint:
    health:
      show-details: always
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true