spring:
  application:
    name: inventory-service
  data.mongodb:
    authentication-database: admin
    username: username
    password: password
    database: inventory
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: 'classpath*:graphql/**/'
  profiles:
    include:
      - common
management.health.circuitbreakers.enabled: true
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    java:
      enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
server:
  shutdown: graceful
  port: 8083
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB
  use-forward-headers: true

  spring.kafka.bootstrap-servers: localhost:9092

logging:
  level:
    root: info
    web: trace
app:
  kafka:
    inventory:
      producer:
        bootstrapServers: ${KAFKA_INVENTORY_PRODUCER_BOOTSTRAP_SERVER:localhost:9092}
        topic: ${KAFKA_INVENTORY_PRODUCER_TOPIC:test}
        idempotence: ${KAFKA_PRODUCER_IDEMPOTENCE:true}
      consumer:
        bootstrapServers: ${KAFKA_INVENTORY_CONSUMER_BOOTSTRAP_SERVER:localhost:9092}
        topic: ${KAFKA_INVENTORY_CONSUMER_TOPIC:inventory}
        consumerGroup: ${KAFKA_INVENTORY_CONSUMER_GROUP:inventory-consumer}