spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  application:
    name: inventory-service
  data.mongodb:
    authentication-database: admin
    username: username
    password: password
    database: brewery
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: 'classpath*:graphql/**/'
  profiles:
    include:
      - common
    active:
      - mongo-reactive

server:
  port: ${DEFAULT__APP__PORT:8083}

spring.kafka.bootstrap-servers: localhost:9092

app:
  kafka:
    inventory:
      consumer:
        bootstrapServers: ${KAFKA_INVENTORY_CONSUMER_BOOTSTRAP_SERVER:localhost:9092}
        topic: ${KAFKA_INVENTORY_CONSUMER_TOPIC:brewery-brew-event}
        consumerGroup: ${KAFKA_INVENTORY_CONSUMER_GROUP:inventory-consumer}
  mongo-service:
    circuit-breaker:
      failureRateThreshold: ${CB__MONGO_SERVICE__FAILURE_RATE_THRESHOLD:10}
      permittedNumberOfCallsInHalfOpenState: ${CB__MONGO_SERVICE__PERMIT_NO_OF_CALL_IN_HALF_OPEN_STATE:${app.default.circuit-breaker.permittedNumberOfCallsInHalfOpenState}}
      slidingWindowSize: ${CB__MONGO_SERVICE__SLIDING_WINDOW_SIZE:${app.default.circuit-breaker.slidingWindowSize}}
      slidingWindowType: ${CB__MONGO_SERVICE__SLIDING_WINDOW_TYPE:${app.default.circuit-breaker.slidingWindowType}}
      minimumNumberOfCalls: ${CB__MONGO_SERVICE__MIN_NO_OF_CALLS:${app.default.circuit-breaker.minimumNumberOfCalls}}
      slowCallRateThreshold: ${CB__MONGO_SERVICE__SLOW_CALL_RATE_THRESHOLD:${app.default.circuit-breaker.slowCallRateThreshold}}
      slowCallDurationThreshold: ${CB__MONGO_SERVICE__SLOW_CALL_DURATION_THRESHOLD:10000}
      maxWaitDurationInHalfOpenState: ${CB__MONGO_SERVICE__MAX_WAIT_DURATION_IN_HALF_OPEN_STATE:${app.default.circuit-breaker.maxWaitDurationInHalfOpenState}}
    time-limiter:
      timeoutDuration: ${TL__MONGO_SERVICE__TIMEOUT_DURATION:500}
    retry:
      maxAttempts: ${RT__MONGO_SERVICE__MAX_ATTEMPT:${app.default.retry.maxAttempts}}
