logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,${app.default.timezone}
    # ongoing issue sleuth to micrometer transition
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: info
    web: info
    org:
      springframework.data:
        mongodb.core.ReactiveMongoTemplate: DEBUG
      mongodb.driver.connection: DEBUG

spring:
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: 'classpath*:graphql/**/'

management:
  health:
    circuitbreakers:
      enabled: true
  tracing.sampling.probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      sla:
        http:
          server:
            requests: 1ms,5ms
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    java:
      enabled: true
    git:
      enabled: true
      mode: full

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
server:
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB
  use-forward-headers: true
app:
  default:
    timezone: ${APP__TIMEZONE:UTC}
    circuit-breaker:
      failureRateThreshold: ${CB__DEFAULT__FAILURE_RATE_THRESHOLD:50}
      permittedNumberOfCallsInHalfOpenState: ${CB__DEFAULT__PERMIT_NO_OF_CALL_IN_HALF_OPEN_STATE:10}
      slidingWindowSize: ${CB__DEFAULT__SLIDING_WINDOW_SIZE:100}
      slidingWindowType: ${CB__DEFAULT__SLIDING_WINDOW_TYPE:COUNT_BASED}
      minimumNumberOfCalls: ${CB__DEFAULT__MIN_NO_OF_CALLS:100}
      slowCallRateThreshold: ${CB__DEFAULT__SLOW_CALL_RATE_THRESHOLD:100}
      slowCallDurationThreshold: ${CB__DEFAULT__SLOW_CALL_DURATION_THRESHOLD:40}
      maxWaitDurationInHalfOpenState: ${CB__DEFAULT__MAX_WAIT_DURATION_IN_HALF_OPEN_STATE:100}
    time-limiter:
      timeoutDuration: ${TL__DEFAULT__TIMEOUT_DURATION:500}
    retry:
      maxAttempts: ${RT__DEFAULT__MAX_ATTEMPT:3}