spring:
  application:
    name: beer-service
  data.mongodb:
    authentication-database: admin
    username: username
    password: password
    database: brewery
  profiles:
    include:
      - common
    active:
      - inventory-client-service
server:
  port: 8080

spring.kafka.bootstrap-servers: localhost:9092
app:
  kafka:
    beer:
      producer:
        bootstrapServers: ${KAFKA_INVENTORY_PRODUCER_BOOTSTRAP_SERVER:localhost:9092}
        topic: ${KAFKA_INVENTORY_PRODUCER_TOPIC:brewery-brew-event}
        idempotence: ${KAFKA_PRODUCER_IDEMPOTENCE:true}