name: Add Comment

on:
  workflow_call:
    inputs:
      comment:
        required: true
        type: string

jobs:
  add_comment:
    if: '!contains(github.event.comment.body, inputs.comment)'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment: ${{ github.event.comment.body }}"
          echo "Inputs Comment: ${{ inputs.comment }}"
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ inputs.comment }}'
            })