name: Add Comment

on:
  workflow_call:
    inputs:
      comment:
        required: true
        type: string

jobs:
  add_comment:
    if: '!contains(github.event.comment.body, inputs.comment)'
    runs-on: ubuntu-latest
    steps:
      - name: List pull request comments
        id: list-comments
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            console.log(response.data);
            return response.data;
        env:
          COMMENTS: ${{ steps.list-comments.outputs.returnValue }}
      - run: |
          echo "Comment: ${{ github.event.comment }}"
          echo "Inputs Comment: ${{ inputs.comment }}"
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ inputs.comment }}'
            })