name: Add Comment

on:
  workflow_call:
    inputs:
      comment:
        required: true
        type: string

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Get existing comments
        id: get_existing_comments
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            console.log(response.data);
            return response.data;
      - uses: actions/github-script@v6
        if: ${{ !contains(steps.get_existing_comments.outputs['comments.*.body'], inputs.comment) }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ inputs.comment }}'
            })