name: beer-service

on:
  push:
    branches: [ "**" ]
    paths: [ "pom.xml","model/**","common/**","beer-service/**",".github/workflows/beer-service.yml" ]
  pull_request:
    branches: [ "**" ]
    paths: [ "pom.xml","model/**","common/**","beer-service/**",".github/workflows/beer-service.yml" ]


jobs:

  beer-service:
    uses: ./.github/workflows/common-build.yml
    with:
      service-name: 'beer-service'
    secrets: inherit

  docker:
    needs: beer-service
    if: ${{github.event_name != 'pull_request' &&  success()}}
    uses: ./.github/workflows/common-docker.yml
    with:
      service-name: 'beer-service'
      version: ${{ needs.beer-service.outputs.sha }}
    secrets: inherit

  docker-latest:
    needs: beer-service
    if: ${{github.event_name != 'pull_request' &&  success() && github.ref == 'refs/heads/main'}}
    uses: ./.github/workflows/common-docker.yml
    with:
      service-name: 'beer-service'
      version: latest
    secrets: inherit