name: Build and Test

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      service-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Get current version
        run: echo "::set-env name=current_version::$(date +"%Y.%m.%d")-$(git rev-parse --short HEAD)"
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ env.current_version }}
      - name: Update Properties
        run: mvn versions:update-properties
      - name: Commit version update
        run: git commit -am "updating version"
      - name: Compile
        run: mvn -B -pl ${{ inputs.service-name }} -am clean install --file pom.xml
      - name: Build Docker image
        run: mvn -B -pl ${{ inputs.service-name }} -DskipTests spring-boot:build-image --file pom.xml
