name: Build and Test

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      service-name:
        required: true
        type: string
      sha:
        required: false
        type: string
    secrets:
      docker-username:
        required: true
      docker-password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Allow job user to access Docker directory
        run: sudo chmod 777 /var/lib/docker
      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ inputs.service-name }}-maven
          restore-keys: ${{ inputs.service-name }}-maven
      - name: Cache Docker Images
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ inputs.service-name }}-docker
          restore-keys: ${{ inputs.service-name }}-docker
      - name: Compile
        run: mvn -B -pl ${{ inputs.service-name }} -DskipTests -am clean compile --file pom.xml
      - name: Test
        run: mvn -B -pl ${{ inputs.service-name }} -am clean test --file pom.xml
      - name: Package
        run: mvn -B -pl ${{ inputs.service-name }} -am -DskipTests clean install --file pom.xml

  docker:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Allow job user to access Docker directory
        run: sudo chmod 777 /var/lib/docker
      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ inputs.service-name }}-maven
          restore-keys: ${{ inputs.service-name }}-maven
      - name: Cache Docker Images
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ inputs.service-name }}-docker
          restore-keys: ${{ inputs.service-name }}-docker
      - name: Build Docker image
        run: mvn -B -pl ${{ inputs.service-name }} -DskipTests spring-boot:build-image --file pom.xml
      - name: Login to DockerHub
        run: echo ${{ secrets.docker-password }} | docker login -u ${{ secrets.docker-username }} --password-stdin
      - name: Push Docker image
        run: docker push docker.io/${{ secrets.docker-username }}/${{ inputs.service-name }}:${{ inputs.sha }}

  docker-latest:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Allow job user to access Docker directory
        run: sudo chmod 777 /var/lib/docker
      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ inputs.service-name }}-maven
          restore-keys: ${{ inputs.service-name }}-maven
      - name: Cache Docker Images
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ inputs.service-name }}-docker
          restore-keys: ${{ inputs.service-name }}-docker
      - name: Build Docker image
        run: mvn -B -pl ${{ inputs.service-name }} -DskipTests -Dversion.number=latest spring-boot:build-image --file pom.xml
      - name: Login to DockerHub
        run: echo ${{ secrets.docker-password }} | docker login -u ${{ secrets.docker-username }} --password-stdin
      - name: Push Docker image
        run: docker push docker.io/${{ secrets.docker-username }}/${{ inputs.service-name }}:latest