name: Build and Test

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      service-name:
        required: true
        type: string
      sha:
        required: false
        type: string
    secrets:
      docker-username:
        required: true
      docker-password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha }}
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: echo sha
        run: |
          echo ${{ inputs.sha }}
          echo ${{ inputs.service-name }}
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ inputs.sha }}
      - name: Compile
        run: mvn -B -pl ${{ inputs.service-name }} -am clean install --file pom.xml
      - name: Build Docker image
        run: mvn -B -pl ${{ inputs.service-name }} -DskipTests spring-boot:build-image --file pom.xml
      - name: Login to DockerHub
        run: echo ${{ secrets.docker-password }} | docker login -u ${{ secrets.docker-username }} --password-stdin
      - name: echo sha
        run: |
          echo ${{ inputs.sha }}
          echo ${{ inputs.service-name }}
      - name: Push Docker image
        run: docker push docker.io/${{ secrets.docker-username }}/${{ inputs.service-name }}:${{ inputs.sha }}