name: Build and Test

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      service-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      sha: ${{ steps.sha.outputs.SHA }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Get SHA
        id: sha
        run: echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Compile
        run: mvn -B -pl ${{ inputs.service-name }} -DskipTests -am clean compile --file pom.xml
      - name: Test
        run: mvn -B -pl ${{ inputs.service-name }} -am clean install --file pom.xml
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.service-name }}-${{ github.run_id }}
          path: ~/.m2/repository/com/brewery
          retention-days: 1

  label-success:
    needs: build
    if: ${{github.event_name == 'pull_request' &&  success()}}
    uses: ./.github/workflows/common-add-label.yml
    with:
      label: ${{ inputs.service-name }}_build-complete
      remove-label: ${{ inputs.service-name }}_build-fail

  label-failure:
    needs: build
    if: ${{github.event_name == 'pull_request' &&  failure()}}
    uses: ./.github/workflows/common-add-label.yml
    with:
      label: ${{ inputs.service-name }}_build-fail
      remove-label: ${{ inputs.service-name }}_build-complete