name: Docker

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '20'
      service-name:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.service-name }}-${{ github.run_id }}
          path: ~/.m2/repository/com/brewery
      - name: Build Docker image
        run: mvn -B -pl ${{ inputs.service-name }} -DskipTests -Dversion.number=${{ inputs.version }} spring-boot:build-image --file pom.xml
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push Docker image
        run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service-name }}:${{ inputs.version }}