# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  inventory-service:
    uses: BreweriesFest/brewery-app/.github/workflows/build.yml@refactor
    with:
      service-name: 'inventory-service'
      event-number: ${{ github.event.number }}

  beer-service:
    uses: BreweriesFest/brewery-app/.github/workflows/build.yml@refactor
    with:
      service-name: 'beer-service'
      event-number: ${{ github.event.number }}

  order-service:
    uses: BreweriesFest/brewery-app/.github/workflows/build.yml@refactor
    with:
      service-name: 'order-service'
      event-number: ${{ github.event.number }}

  scheduler:
    uses: BreweriesFest/brewery-app/.github/workflows/build.yml@refactor
    with:
      service-name: 'scheduler'
      event-number: ${{ github.event.number }}