# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  env-setup:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.sha.outputs.SHA }}
    steps:
      - name: Get SHA
        id: sha
        run: echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  inventory-service:
    needs: env-setup
    uses: ./.github/workflows/build.yml
    with:
      service-name: 'inventory-service'
      sha: ${{ needs.env-setup.outputs.sha }}
    secrets:
      docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
      docker-username: ${{ secrets.DOCKERHUB_USERNAME }}

  beer-service:
    needs: env-setup
    uses: ./.github/workflows/build.yml
    with:
      service-name: 'beer-service'
      sha: ${{ needs.env-setup.outputs.sha }}
    secrets:
      docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
      docker-username: ${{ secrets.DOCKERHUB_USERNAME }}

  order-service:
    needs: env-setup
    uses: ./.github/workflows/build.yml
    with:
      service-name: 'order-service'
      sha: ${{ needs.env-setup.outputs.sha }}
    secrets:
      docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
      docker-username: ${{ secrets.DOCKERHUB_USERNAME }}

  scheduler:
    needs: env-setup
    uses: ./.github/workflows/build.yml
    with:
      service-name: 'scheduler'
      sha: ${{ needs.env-setup.outputs.sha }}
    secrets:
      docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
      docker-username: ${{ secrets.DOCKERHUB_USERNAME }}

  comment:
#    needs: [inventory-service, beer-service, order-service, scheduler]
    if: ${{ always() && github.event_name == 'pull_request' }}
    uses: ./.github/workflows/add_comment.yml
    with:
      comment: '👋 Thanks for for raising PR!'