# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  inventory-service:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set version
        run: mvn versions:set -DnewVersion=${GITHUB_HEAD_REF}.${GITHUB_SHA::7} -DprocessDependencies=false
      - name: Compile
        run: mvn -B -pl inventory-service -am clean install --file pom.xml
      - name: Build Docker image
        run: mvn -B -pl inventory-service -DskipTests spring-boot:build-image --file pom.xml

  beer-service:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set version
        run: mvn versions:set -DnewVersion=${GITHUB_HEAD_REF}.${GITHUB_SHA::7} -DprocessDependencies=false
      - name: Compile
        run: mvn -B -pl beer-service -am clean install --file pom.xml
      - name: Build Docker image
        run: mvn -B -pl beer-service -DskipTests spring-boot:build-image --file pom.xml

  order-service:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set version
        run: mvn versions:set -DnewVersion=${GITHUB_HEAD_REF}.${GITHUB_SHA::7} -DprocessDependencies=false
      - name: Compile
        run: mvn -B -pl order-service -am clean install --file pom.xml
      - name: Build Docker image
        run: mvn -B -pl order-service -DskipTests spring-boot:build-image --file pom.xml