name: scheduler

on:
  push:
    branches: [ "**" ]
    paths: [ "pom.xml","model/**","common/**","scheduler/**",".github/workflows/service-scheduler.yml" ]
  pull_request:
    branches: [ "**" ]
    paths: [ "pom.xml","model/**","common/**","scheduler/**",".github/workflows/service-scheduler.yml" ]


jobs:

  scheduler:
    uses: ./.github/workflows/common-build.yml
    with:
      service-name: 'scheduler'
    secrets: inherit

  docker:
    needs: scheduler
    if: ${{github.event_name != 'pull_request' &&  success()}}
    uses: ./.github/workflows/common-docker.yml
    with:
      service-name: 'scheduler'
      version: ${{ needs.scheduler.outputs.sha }}
    secrets: inherit

  docker-latest:
    needs: scheduler
    if: ${{github.event_name != 'pull_request' &&  success() && github.ref == 'refs/heads/main'}}
    uses: ./.github/workflows/common-docker.yml
    with:
      service-name: 'scheduler'
      version: latest
    secrets: inherit