name: Build Version

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
    outputs:
      sha:
        description: "latest commit"
        value: ${{ jobs.version.outputs.sha }}

jobs:
  version:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Map the job outputs to step outputs
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Get current version
        run: echo "current_version=$(date +"%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ env.current_version }}
      - name: Update Properties
        run: mvn versions:update-properties
      - name: Commit version update
        run: |
          git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          git commit -am "updating version"
          git push origin main
      - name: Get SHA
        id: sha
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo git rev-parse HEAD